### ISSUE TITLE
No device detected

### ISSUE THREAD

**Issue by DarthJahus** [ventorvar/pyvkb#4]
* pyvkb version: 0.1.0
* Python version: 3.10
* Operating System: Windows 10 build 19044.1466

### Description

When I use `vkb list`, nothing is shown (seems like my device is not detected). What are the requirements for this to work?

### What I Did

Install `pyvkb`
Plug my VKB NXT (with other modules attached to it)
Use `pyvkb list`

**Comment by ventorvar** [comment]
Hmmm. There should always be _something_ shown. For instance, if I disconnect everything I see the following:

```
$ vkb list
No VKB devices found
```

After reconnecting (tested on Windows 11 22000.424 with Python 3.10):

```
$ vkb list
  0:  VKB-Sim Gladiator K LH  (9f836ef0-6e76-11ec-8006444553540000)
  1:  VKB-Sim Gladiator K  (9f83bd10-6e76-11ec-800a444553540000)
```

Are you using anything that could be hiding the devices like HidHide/HidGuardian/devreorder?

**Comment by DarthJahus** [comment]
Interesting. I have tried `vkb list` on 3 different computers. With and without admin privilege, with and without Windows Defender. I have installed neither HidHIDE nor HidGuardian, nor devreorder.

The result is this, on all of them:

```
C:\>vkb list

C:\>
```

Computer 1: Python `3.10.0`, Windows 10 `19044.1526`
Computer 2: Python `3.8.9`, Windows 10 `19044.1526`
Computer 3: Python `3.8.9`, Windows 11 `22000.469`

Is there anything that has to be installed for the script to function? Any dependencies? I remain available if anything is needed for investigation.

**Comment by DarthJahus** [comment]
I have investigated a bit and explored the code. Then seeing there was nothing to print `No VKB devices found`, I have compared the code I have (installed through `pip install pyvkb`) and the one in this repository. And they seem very different.

I will report back after installing the version from this repo.

**Comment by DarthJahus** [comment]
Here is what I have done:

1. Uninstall the VKB script installed through `pip`
1. `git clone` this repository
1. `python .\setup.py install`
1. `vkb list`
> `No VKB devices found`

So I have checked, as suggested by @[tiberiusteng](https://github.com/tiberiusteng) on his vkb-msfs-led rope ([here](https://github.com/tiberiusteng/vkb-msfs-led/issues/1#issuecomment-1034440166)), I have checked the device ID, which shows as 0234 in **VKBDevCfg**.

I then added a new class in `gladiatork` module with `PRODUCT_ID = 0x0234` and referenced it in `defs.py` module.

Then uninstalled old version and installed the modified one via `python .\setup.py install`.

```
PS …\VKB\pyvkb> vkb list
  0:  VKBsim Gladiator NXT R SEM THQ FSM.GA  (2efa30f0-843e-11ec-8006444553540000)
  1:  VKBsim Gladiator NXT R SEM THQ FSM.GA  (2efa5800-843e-11ec-8007444553540000)
```

Here we go 😄

**Edit:** The old version does work as well, after adding the new product ID.

---

This said, I believe the version on PyPi should be updated.

Thank you very much for your work. I don't know if it's known in VKB forums, but it totally should be acknowledged by VKB and used more widely – especially for LED controls – now that VKB has more devices.

**Comment by ventorvar** [comment]
Awesome stuff! PyPi will definitely get updated, and I'll add in your new device. While I've got you and if you're up for assisting:

- Which device(s) do you have? (is it this thing? https://vkbcontrollers.com/?product=gnx-dual-thq-sem-fsm-ga-combo)
- What LEDs are available on the device (labeled picture would be awesome, or just short description) and what is their LED number in VKB device config? (you can enable the developer mode and use the Test > Misc > LED fast test to figure these out)

for example on the VKB Gladiator Ks I've got:
```    
    LED_BASE = 0
    LED_TOP = 10
    LED_POV = 11
```

**Comment by DarthJahus** [comment]
My device is a custom configuration, with [VKB-NXT](https://flightsimcontrols.com/product/gladiator-nxt/) + [GNX-THQ](https://flightsimcontrols.com/product/gnx-thq-throttle-quadrant/) + [GNX-SEM](https://flightsimcontrols.com/product/gnx-sem-side-extension-module/) + [FSM-GA](https://flightsimcontrols.com/product/gnx-fsm-ga-front-switchboard-module-general-aviation/) (in this order but the configurator orders them as NXT SEM THQ FSM.GA).

**VKBDevCfg** shows PID `0234`.

* VKB-NXT has:
```
LED_BASE = 0
```
> The base has 2 LEDs, but I can't find a way to program the first one.

* The grip (SCG) has 2 LEDs (`Base = 10`, `LedsN = 2`).
```
LED_TOP = 10
LED_POV = 11
```
> `LED_TOP` only has Red color. `LED_POV` is **RGB**.

* The SEM has 8 LEDs (`Base = 12`, `LedsN = 8`). The first LED, `12`, is the top left LED, then they are sequentially sorted.
> The SEM module LEDs only have Green and Red colors. No blue.

* The THQ module has no LEDs.

* The FSM.GA module has 12 LEDs (`Base = 20`, `LedsN = 12`). Again, they are sorted sequentially starting from the top left, then the top right, then the center ones from top to bottom.
> The FSM-GA module LEDs only have Green and Red colors. No blue.

So each module has its number of LEDs. As of the ID numbers, they depend on the LED `Base` number, that can be calculated by adding the previous `Base` with previous `LedsN`.

It would be interesting to get the Product ID of multiple configurations and include them (from the forums or /r/HOTAS?). Maybe instead of hard-coding the modules, use a configuration JSON file or similar. Just an idea.

Thank you again for all this work. It's much appreciated. You can contact me any time if you need information.

![IMG_20220211_165942](https://user-images.githubusercontent.com/7353366/153630514-20a87eb8-e8ec-4055-a9fa-fed116df4168.jpg)

**Comment by ventorvar** [comment]
awesome, thanks! 

config file makes a lot of sense, and really the classes are just for 
convenience sake and aren't really used for anything... - ill take a whack at converting since in any case it would be easier for non-programmers to update in the future.
